### ISSUE TITLE
Does not compile or pip install using MacOS Apple Silicon (MacOS 12.1)

### ISSUE THREAD

**Issue by tburcham-alidabio** [jfjlaros/tssv#4]
To reproduce under MacOS 12.1 Apple M1 Pro, just do a pip3 install tssv==1.1.2
Works fine under Linux (Ubuntu) and MacOS 12.0.1 Apple Intel (i5).
We continue to investigate but hoping that others can fix this faster than me!  Thank you!

===============================

tim@alidamac0 211217 % pip3 install tssv==1.1.2
Collecting tssv==1.1.2
  Using cached tssv-1.1.2.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: biopython>=1.72 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tssv==1.1.2) (1.79)
Requirement already satisfied: requests>=2.19.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tssv==1.1.2) (2.26.0)
Requirement already satisfied: xopen>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tssv==1.1.2) (1.2.1)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from biopython>=1.72->tssv==1.1.2) (1.21.4)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.19.1->tssv==1.1.2) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.19.1->tssv==1.1.2) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.19.1->tssv==1.1.2) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.19.1->tssv==1.1.2) (2.0.9)
Using legacy 'setup.py install' for tssv, since package 'wheel' is not installed.
Installing collected packages: tssv
    Running setup.py install for tssv ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/py/0qndqsl15_175_94p5thghxh0000gn/T/pip-install-x0nrgb5g/tssv_07c6b51866e541a28af25ace61ee8470/setup.py'"'"'; __file__='"'"'/private/var/folders/py/0qndqsl15_175_94p5thghxh0000gn/T/pip-install-x0nrgb5g/tssv_07c6b51866e541a28af25ace61ee8470/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/py/0qndqsl15_175_94p5thghxh0000gn/T/pip-record-6uxp_0rb/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/tssv
         cwd: /private/var/folders/py/0qndqsl15_175_94p5thghxh0000gn/T/pip-install-x0nrgb5g/tssv_07c6b51866e541a28af25ace61ee8470/
    Complete output (84 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-universal2-3.10
    creating build/lib.macosx-10.9-universal2-3.10/tssv
    copying tssv/tssv.py -> build/lib.macosx-10.9-universal2-3.10/tssv
    copying tssv/__init__.py -> build/lib.macosx-10.9-universal2-3.10/tssv
    copying tssv/align_pair.py -> build/lib.macosx-10.9-universal2-3.10/tssv
    copying tssv/cli.py -> build/lib.macosx-10.9-universal2-3.10/tssv
    package init file 'extras/annotate/__init__.py' not found (or not a regular file)
    creating build/lib.macosx-10.9-universal2-3.10/tssv_extras
    copying extras/annotate/annotate.py -> build/lib.macosx-10.9-universal2-3.10/tssv_extras
    copying tssv/sgAlign.h -> build/lib.macosx-10.9-universal2-3.10/tssv
    copying tssv/sgAlignSSE.h -> build/lib.macosx-10.9-universal2-3.10/tssv
    running build_ext
    building 'tssv.sg_align' extension
    creating build/temp.macosx-10.9-universal2-3.10
    creating build/temp.macosx-10.9-universal2-3.10/tssv
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c tssv/sgAlign.c -o build/temp.macosx-10.9-universal2-3.10/tssv/sgAlign.o -O3
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c tssv/sgAlignSSE.c -o build/temp.macosx-10.9-universal2-3.10/tssv/sgAlignSSE.o -O3
    In file included from tssv/sgAlignSSE.c:4:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/emmintrin.h:13:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/xmmintrin.h:13:
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:50:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:129:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:159:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:189:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:216:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:239:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:260:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:287:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:310:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:331:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:352:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:373:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:394:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:416:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:439:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_paddsw((__v4hi)__m1, (__v4hi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:461:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_paddusb((__v8qi)__m1, (__v8qi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:483:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_paddusw((__v4hi)__m1, (__v4hi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:504:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_psubb((__v8qi)__m1, (__v8qi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:525:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
        return (__m64)__builtin_ia32_psubw((__v4hi)__m1, (__v4hi)__m2);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/py/0qndqsl15_175_94p5thghxh0000gn/T/pip-install-x0nrgb5g/tssv_07c6b51866e541a28af25ace61ee8470/setup.py'"'"'; __file__='"'"'/private/var/folders/py/0qndqsl15_175_94p5thghxh0000gn/T/pip-install-x0nrgb5g/tssv_07c6b51866e541a28af25ace61ee8470/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/py/0qndqsl15_175_94p5thghxh0000gn/T/pip-record-6uxp_0rb/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/tssv Check the logs for full command output.

**Comment by jfjlaros** [comment]
It seems to me that this issue is related to [this](https://stackoverflow.com/questions/69739415/how-to-get-code-that-uses-x86intrin-h-to-run-on-mac) one.

You could contact the author of the SSE alignment (see [credits](https://tssv.readthedocs.io/en/latest/credits.html)), alternatively, we can drop this from the implementation.

**Comment by jfjlaros** [comment]
Perhaps you can try this [branch](https://github.com/jfjlaros/tssv/tree/nosse).

**Comment by tburcham-alidabio** [comment]
This branch seems to be working fine!
Will continue to test -- thank you!
Tim
